---
- name: Enable firewall access
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 8086/tcp
    - 25826/udp

- name: Setup InfluxDB
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd configuration and restart InfluxDB

- name: Ensure InfluxDB is up
  systemd:
    name: influxdb
    state: started
    enabled: true
    daemon_reload: true
