---
- name: Add datastax repository
  yum_repository:
    name: datastax
    description: DataStax Repo for DataStax Enterprise
    file: datastax
    baseurl: https://rpm.datastax.com/enterprise
    gpgcheck: no

- name: Create a cassandra system group
  group:
    name: cassandra
    state: present
    system: true

- name: Create a cassandra system user
  user:
    name: cassandra
    shell: /bin/bash
    groups: cassandra
    system: true

- name: Install dependecies
  yum:
    name:
      - java-1.8.0-openjdk.x86_64
      - mlocate
      - bash-completion
      - NetworkManager
      - lvm2
      - firewalld
      - jemalloc
      - wget
      - unzip
    state: present
  register: install_dependecies_packages
  until: install_dependecies_packages is not failed
  retries: 5

- name: Put services on desired state
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop:
    - { name: 'NetworkManager', state: 'started', enabled: true }
    - { name: 'firewalld', state: 'stopped', enabled: false }

- name: Setup kernel parameters
  sysctl:
    name: "{{ item.parameter }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { parameter: 'net.ipv4.tcp_keepalive_time', value: '60' }
    - { parameter: 'net.ipv4.tcp_keepalive_probes', value: '3' }
    - { parameter: 'net.ipv4.tcp_keepalive_intvl', value: '10' }
    - { parameter: 'net.core.rmem_max', value: '16777216' }
    - { parameter: 'net.core.wmem_max', value: '16777216' }
    - { parameter: 'net.core.rmem_default', value: '16777216' }
    - { parameter: 'net.core.wmem_default', value: '16777216' }
    - { parameter: 'net.core.optmem_max', value: '40960' }
    - { parameter: 'net.ipv4.tcp_rmem', value: '4096 87380 16777216' }
    - { parameter: 'net.ipv4.tcp_wmem', value: '4096 65536 16777216' }
    - { parameter: 'vm.zone_reclaim_mode', value: '0' }
    - { parameter: 'vm.swappiness', value: '1' }
    - { parameter: 'vm.max_map_count', value: '1048575' }
    
- name: Modify soft and hard limits for cassandra user.
  pam_limits:
    domain: cassandra
    limit_type: '-'
    limit_item: "{{ item.parameter }}"
    value: "{{ item.value }}"
  loop:
    - { parameter: 'memlock', value: 'unlimited' }
    - { parameter: 'nofile', value: '1048576' }
    - { parameter: 'nproc', value: '32768' }
    - { parameter: 'as', value: 'unlimited' }

- name: Get current read-ahead value
  command: blockdev --getra /dev/vdb
  register: read_ahead_result

- name: Set a low value to read-ahead
  command: blockdev --setra 128 /dev/vdb
  when: read_ahead_result.stdout|int > 129

- name: Disable defrag on transparent hugepages
  lineinfile:
    path: /etc/rc.local
    insertafter: '^touch /var/lock/subsys/local'
    line: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Cloud init template to remove FQDN from /etc/hosts
  copy:
    src: hosts.redhat.tmpl
    dest: /etc/cloud/templates/hosts.redhat.tmpl
    owner: root
    group: root
    mode: 0644
  register: cloud_init_template_result

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cloud_init_template_result is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cloud_init_template_result is changed
