---
- name: Grafana initial setup
  hosts: monitoring
  become: true
  gather_facts: false

  tasks:
    - name: Import CollectD role
      import_role:
        name: collectd

    - name: Import Grafana role
      import_role:
        name: grafana
